tosca_definitions_version: tosca_simple_yaml_1_0
description: ''
imports:
- micro: ../../data/micro-tosca-types.yml
topology_template:
  node_templates:
    shipping:
      type: micro.nodes.Service
      requirements:
      - deployment_time: order_db
      - deployment_time: rabbitmq
      - interaction: order_db
    order_db:
      type: micro.nodes.Datastore
    order:
      type: micro.nodes.Service
      requirements:
      - deployment_time: shipping
      - deployment_time: order_db
      - deployment_time: rabbitmq
      - interaction: shipping
      - interaction: order_db
    rabbitmq:
      type: micro.nodes.CommunicationPattern
    gateway:
      type: micro.nodes.CommunicationPattern
      requirements:
      - deployment_time: shipping
  groups:
    edgenodes:
      type: micro.groups.Edge
      members:
      - order
      - gateway
